name: 定期自动登录并发送结果

on:
  schedule:
    - cron: "0 0 */3 * *"  # 每三天运行一次，可以根据需求调整时间
  workflow_dispatch:  # 支持手动触发

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: 检查出环境变量
        run: |
          echo "ACCOUNTS=${{ secrets.ACCOUNTS }}" >> $GITHUB_ENV
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_USER_ID=${{ secrets.TELEGRAM_USER_ID }}" >> $GITHUB_ENV

      - name: 登录并发送结果
        run: |
          #!/bin/bash
          IFS=';' read -r -a ACCOUNTS_array <<< "$ACCOUNTS"
          success_count=0
          failure_count=0
          failed_users=()
          
          for ACCOUNT in "${ACCOUNTS_array[@]}"; do
            IFS=' ' read -r -a credentials <<< "$ACCOUNT"
            SERVER=${credentials[0]}
            USERNAME=${credentials[1]}
            PASSWORD=${credentials[2]}
            
            sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER "echo $USERNAME登录成功"
            if [ $? -eq 0 ]; then
              success_count=$((success_count + 1))
            else
              failure_count=$((failure_count + 1))
              failed_users+=("$USERNAME@$SERVER")
            fi
          done
          
          message="登录完成，成功 $success_count，失败 $failure_count。"
          if [ $failure_count -gt 0 ]; then
            message="$message 失败账户：${failed_users[*]}"
          fi

          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d chat_id=$TELEGRAM_USER_ID -d text="$message"
