name: 手动重置服务器

on:
  workflow_dispatch:

jobs:
  reset_server:
    runs-on: ubuntu-latest
    steps:
      - name: 设置环境变量
        run: |
          echo "ACCOUNTS=${{ secrets.ACCOUNTS }}" >> $GITHUB_ENV

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: 定义SSH函数
        run: |
          reset_server () {
            local SERVER=$1
            local USERNAME=$2
            local PASSWORD=$3
            
            sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no "$USERNAME@$SERVER" "
              pkill -kill -u $USERNAME
              chmod -R 755 ~/* 
              chmod -R 755 ~/.* 
              rm -rf ~/.* 
              rm -rf ~/*
              exit
            "
          }

      - name: 重置服务器
        run: |
          IFS=';' read -r -a ACCOUNTS_array <<< "$ACCOUNTS"
          
          for ACCOUNT in "${ACCOUNTS_array[@]}"; do
            IFS=' ' read -r -a credentials <<< "$ACCOUNT"
            SERVER=${credentials[0]}
            USERNAME=${credentials[1]}
            PASSWORD=${credentials[2]}
            
            reset_server "$SERVER" "$USERNAME" "$PASSWORD"
          done
